### ISSUE TITLE
Please make a release, because 0.3.0 isn't compatible with fluidsynth 2.x

### ISSUE THREAD

**Issue by yurivict** [x42/gmsynth.lv2#2]
See https://ptpb.pw/yOuk

**Comment by yurivict** [comment]
FYI On FreeBSD fluidsynth is unbundled.

Please also unbundle fluidsynth, because it's best to use the package-installed version.

**Comment by x42** [comment]
Please do ***NOT*** use system-wide fluidsynth nor dynamically link. Plugins must be self-contained.

The plugin does include a dedicated, patched, version of fluidsynth with hidden symbols, so that the plugin won't interfere with any other plugins that may also use fluidsynth. 

 e.g. fluidsynth has a global shared cache. That is fine for applications but it is not suitable for use by different plugins that may not know about each other when loaded into the same host.

**Comment by yurivict** [comment]
Ok, thanks.

**Comment by x42** [comment]
PS. a longer explanation of the issue is http://lists.ardour.org/pipermail/ardour-users-ardour.org/2018-November/028948.html

**Comment by yurivict** [comment]
Thank you, Robin,

I changed it back to bundled in the FreeBSD port.

**Comment by x42** [comment]
I'll make a release regardless sometime soon (to include the fluidsynt 2.0.2 update)
